spring:
  enable-multiple-database-mode: true
  primary:
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test_master
      username: namnx
      password: namnx
      hikari:
        hikariMaximumPoolSize: 50
        leakDetectionThreshold: 5000
        connectionTestQuery: SELECT 1
  replica:
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test_replica #using url of load balancer for read-only replication groups
      username: namnx
      password: namnx
